name: Build, Push and Deploy to GCP

on:
  push:
    branches: [ main ]

permissions:
  contents: read
  id-token: write  # Requis pour Workload Identity Federation

jobs:
  build-push-deploy:
    runs-on: ubuntu-latest

    env:
      PROJECT_ID: customer-churn-mlops-s6e3-rd
      REGION: europe-west1
      REPOSITORY: customer-churn
      IMAGE: api
      SERVICE: customer-churn-api

    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Authenticate to Google Cloud (Workload Identity Federation)
        uses: google-github-actions/auth@v2
        with:
          workload_identity_provider: projects/86656814713/locations/global/workloadIdentityPools/github-pool/providers/github-provider
          service_account: github-actions-sa@customer-churn-mlops-s6e3-rd.iam.gserviceaccount.com

      - name: Configure Docker for Artifact Registry
        run: gcloud auth configure-docker ${{ env.REGION }}-docker.pkg.dev --quiet

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./dockerfile
          push: true
          tags: ${{ env.REGION }}-docker.pkg.dev/${{ env.PROJECT_ID }}/${{ env.REPOSITORY }}/${{ env.IMAGE }}:${{ github.sha }}

      - name: Deploy to Cloud Run
        uses: google-github-actions/deploy-cloudrun@v2
        with:
          service: ${{ env.SERVICE }}
          region: ${{ env.REGION }}
          image: ${{ env.REGION }}-docker.pkg.dev/${{ env.PROJECT_ID }}/${{ env.REPOSITORY }}/${{ env.IMAGE }}:${{ github.sha }}
          flags: --port=8000 --memory=512Mi --allow-unauthenticated
